import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/app/(component)/Sidebar";
import Header from "@/app/(component)/Header";
import Tabs from "@/app/(component)/Tabs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sf antialiased`}>
        <div className="flex">
          <Sidebar />
          <div className="flex-1">
            <Header />
            <Tabs />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
